### PR TITLE
Gitlab support

### PR DESCRIPTION
**Pull request by ngoyal16**
system now support Gitlab as repo

### CODE REVIEW

**Comment by githubsaturn** [comment]
Mind adding gitlab to the UI as well?
 Currently, UI reads "github/bitbucket"

**Comment by ngoyal16** [comment]
ok

**Comment by githubsaturn** [comment]
@ngoyal16 
I am confused, why Github is showing bodyparser part as a new diff??
It's already merged in the other Pull Request. It's merged to master branch:
https://github.com/githubsaturn/captainduckduck/blob/master/app-backend/src/routes/WebhooksRouter.js#L2

Any idea why?

**Comment by ngoyal16** [comment]
actually, i pushed it from a different system so it wasn't having the updated code

**Comment by githubsaturn** [comment]
Ok then, I'll manually merge this tomorrow a give it a thorough read to make sure we don't have duplication.

**Comment by ngoyal16** [comment]
ok

**Pull request merged**
