### PR TITLE
Add Redis oneclick-app file

### PR DESCRIPTION
**Pull request by gnuns**
solve #108 
Hi, @githubsaturn!
As the files inside app-frontend and app-backend/dist are the same, I assumed that you run `gulp build` before releasing new versions, so I've added the source code only to app-frontend, but I can update the PR with both files if it's needed.

### CODE REVIEW

**Comment by githubsaturn** [comment]
Thanks @gnuns 

We also need to add password. Unfortunately, default redis image does not support environmental variables for setting up authentication. See https://github.com/docker-library/redis/issues/46

However, since we can create a custom dockerfile in one click app, we can use this workaround:
https://github.com/docker-library/redis/issues/46#issuecomment-211599210

**Comment by gnuns** [comment]
Most users does not use Redis servers with password. May I set the password field as 'optional'?

**Comment by githubsaturn** [comment]
Yes. Surely optional.

**Comment by gnuns** [comment]
Done!

**Pull request merged**
