### PR TITLE
Ruby apps support

### PR DESCRIPTION
**Pull request by juanantoniofj**
Add support for ruby apps built on Rack.

Added dockerfile for ruby apps with some extra apk dependencies for building bundled native libraries.
Added new entry in TemplateHelper for ruby and sample app.

### CODE REVIEW

**Comment by githubsaturn** [comment]
@juanantoniofj 
This is great! Thanks for adding this. Just some questions

- I noticed that you're using rackup command, do ruby projects always support this command? 
- Based on my 30sec googling, there is a `RACK_ENV` environmental variable that needs to be set to `production`. Also, in case of Rails, there is `RAILS_ENV`. Don't we have to set these values?

Disclaimer: I haven't written a single line of Ruby. So my question might be too dumb, but I want to make sure that this is as generic as possible - without any presumptions about the project.

**Comment by juanantoniofj** [comment]
Thanks! I am not a Ruby expert either but i decided to give it a chance, so maybe someone can help us to clarify. Anyway, regarding your questions:

- To support the rackup command, the Rack gem has to be installed. I wrote the template using the python template as guideline which is indeed based on Django. Maybe we should rename this template to "rack" instead "ruby"?
- About the RACK_ENV, you are right, we have to set that ENV variable. I will add it.

**Comment by githubsaturn** [comment]
Ok thanks. I try to get hold of someone with Ruby experience to review this.
Cheers

**Comment by geoman2** [comment]
Hello @githubsaturn

Want to send a feature request, is there a way to add the Vulcan JS framework (some sort of Meteor/ReactJS+MongoDB stack) to captainduckduck

Sacha Greif is the author https://blog.vulcanjs.org/@sachagreif

Regards
Geo

**Comment by gnuns** [comment]
Renaming this template to ["rack"](https://rack.github.io/) or "ruby-rack" instead of "ruby" is a good idea.
For Ruby on Rails, a [`puma`](https://github.com/puma/puma) template would be nice too.

**Comment by juanantoniofj** [comment]
I agree, @gnuns . I think ruby-rack would be a better choice, so it would start to set a naming convention for future use for new ruby templates.

@githubsaturn, would you consider a good choice to rename other templates like the python one to something like python-django?

**Comment by githubsaturn** [comment]
Great suggestion guys!

I'll merge this tomorrow and rename the templates. Expect this in v0.5 in next few days! :+1:

**Pull request merged**
