### PR TITLE
Add the Captain Duck Duck Slack Workspace to Readme

### PR DESCRIPTION
**Pull request by simonfrey**
As I sometimes would love to get help from the CDD community I created the Captain Duck Duck Slack Workspace.

Please join the slack, so I can make you owners of it!

https://join.slack.com/t/captainduckduck/shared_invite/enQtMzc0NDIzODI2ODY1LWY2NzQyYzMwNTVmYTllMDM4YjE3ZDA4NWQ1ZjI1M2Y5ZTVmZDc1NDRkZWMxMTYzYjkxNzY0OWUyNDRkZmZiOTc

### CODE REVIEW

**Comment by simonfrey** [comment]
Saw the issue right now

**Comment by stunjiturner** [comment]
I am trying to join the slack channel but its not sending me back a invite? any email to contact?

**Comment by githubsaturn** [comment]
See #13

**Comment by githubsaturn** [comment]
The link in this issue was wrong. I just removed it.  Did you use this link or the link in #13?

**Comment by stunjiturner** [comment]
13

S Tunji Turner
sightuary
@sightuary

**Comment by githubsaturn** [comment]
I just re-tested it, the link works fine.

**Comment by githubsaturn** [comment]
After entering your email, you will receive an email from Slack to verify your account. It might go to your Spam folder. But I tested the link and registration works fine.

**Comment by stunjiturner** [comment]
I know how it works, I just signed up with Apollographql and the link worked dined and I am signed in the workspace with my other ten

S Tunji Turner
sightuary
@sightuary

**Pull request closed without merging**
