### PR TITLE
Stateless (direct) deployment

### PR DESCRIPTION
**Pull request by Rusfighter**
Few remarks: handle the reading/storaging the authtoken outside the deploy/login functions so is less coupled

- This can be useful if you want to integrate CI/CD pipeline.
- Makes automatic deployment possible for mono-repos

### CODE REVIEW

**Comment by githubsaturn** [comment]
Thanks! I'll go over this and merge this in next couple of days.

**Comment by Rusfighter** [comment]
I want to contribute more to this project, however i was wondering how you think about using transpilers such as babel to avoid some "callback hells"?

**Comment by githubsaturn** [comment]
Backend app uses Node 8, so Promises are natively supported. For CLI app, it's just the deploy command that is getting a little bit callback-hellish, so I think we should keep this as vanilla as is - unless it gets to an unmanageable state.

**Comment by Rusfighter** [comment]
> For CLI app, it's just the deploy command that is getting a little bit callback-hellish

The problem here is that you don't know what version user uses, therefor I think it is better to use a transpiler and target low version nodejs and plus it makes life easier for devs ;). Btw I don't know since what nodejs version `const` and `let` is supported, but i can assume some users with old node env will get some errors.

**Comment by githubsaturn** [comment]
Yea I noticed your `const` and `let` - they are supported in NodeJS 4+. So it's supported for a majority of people. But I'll revert it anyways to keep things as compatible as before.

**Pull request merged**
